/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as FlowRouteImport } from './routes/flow'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as TimelineRouteImport } from './routes/timeline'
import { Route as ToolsRouteImport } from './routes/tools'
import { Route as VerifyEmailRouteImport } from './routes/verify-email'
import { Route as CategoriesSlugRouteImport } from './routes/categories/$slug'
import { Route as GuidesIndexRouteImport } from './routes/guides/index'
import { Route as GuidesSlugRouteImport } from './routes/guides/$slug'
import { Route as NewsIndexRouteImport } from './routes/news/index'
import { Route as NewsSlugRouteImport } from './routes/news/$slug'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const FlowRoute = FlowRouteImport.update({
  id: '/flow',
  path: '/flow',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const TimelineRoute = TimelineRouteImport.update({
  id: '/timeline',
  path: '/timeline',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsRoute = ToolsRouteImport.update({
  id: '/tools',
  path: '/tools',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyEmailRoute = VerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriesSlugRoute = CategoriesSlugRouteImport.update({
  id: '/categories/$slug',
  path: '/categories/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const GuidesIndexRoute = GuidesIndexRouteImport.update({
  id: '/guides/',
  path: '/guides/',
  getParentRoute: () => rootRouteImport,
} as any)
const GuidesSlugRoute = GuidesSlugRouteImport.update({
  id: '/guides/$slug',
  path: '/guides/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsIndexRoute = NewsIndexRouteImport.update({
  id: '/news/',
  path: '/news/',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsSlugRoute = NewsSlugRouteImport.update({
  id: '/news/$slug',
  path: '/news/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/flow': typeof FlowRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/timeline': typeof TimelineRoute
  '/tools': typeof ToolsRoute
  '/verify-email': typeof VerifyEmailRoute
  '/categories/$slug': typeof CategoriesSlugRoute
  '/guides/$slug': typeof GuidesSlugRoute
  '/news/$slug': typeof NewsSlugRoute
  '/guides/': typeof GuidesIndexRoute
  '/news/': typeof NewsIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/flow': typeof FlowRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/timeline': typeof TimelineRoute
  '/tools': typeof ToolsRoute
  '/verify-email': typeof VerifyEmailRoute
  '/categories/$slug': typeof CategoriesSlugRoute
  '/guides/$slug': typeof GuidesSlugRoute
  '/news/$slug': typeof NewsSlugRoute
  '/guides': typeof GuidesIndexRoute
  '/news': typeof NewsIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/flow': typeof FlowRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/timeline': typeof TimelineRoute
  '/tools': typeof ToolsRoute
  '/verify-email': typeof VerifyEmailRoute
  '/categories/$slug': typeof CategoriesSlugRoute
  '/guides/$slug': typeof GuidesSlugRoute
  '/news/$slug': typeof NewsSlugRoute
  '/guides/': typeof GuidesIndexRoute
  '/news/': typeof NewsIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/flow'
    | '/login'
    | '/profile'
    | '/timeline'
    | '/tools'
    | '/verify-email'
    | '/categories/$slug'
    | '/guides/$slug'
    | '/news/$slug'
    | '/guides/'
    | '/news/'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/flow'
    | '/login'
    | '/profile'
    | '/timeline'
    | '/tools'
    | '/verify-email'
    | '/categories/$slug'
    | '/guides/$slug'
    | '/news/$slug'
    | '/guides'
    | '/news'
    | '/api/auth/$'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/flow'
    | '/login'
    | '/profile'
    | '/timeline'
    | '/tools'
    | '/verify-email'
    | '/categories/$slug'
    | '/guides/$slug'
    | '/news/$slug'
    | '/guides/'
    | '/news/'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  FlowRoute: typeof FlowRoute
  LoginRoute: typeof LoginRoute
  ProfileRoute: typeof ProfileRoute
  TimelineRoute: typeof TimelineRoute
  ToolsRoute: typeof ToolsRoute
  VerifyEmailRoute: typeof VerifyEmailRoute
  CategoriesSlugRoute: typeof CategoriesSlugRoute
  GuidesSlugRoute: typeof GuidesSlugRoute
  NewsSlugRoute: typeof NewsSlugRoute
  GuidesIndexRoute: typeof GuidesIndexRoute
  NewsIndexRoute: typeof NewsIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/flow': {
      id: '/flow'
      path: '/flow'
      fullPath: '/flow'
      preLoaderRoute: typeof FlowRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/timeline': {
      id: '/timeline'
      path: '/timeline'
      fullPath: '/timeline'
      preLoaderRoute: typeof TimelineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools': {
      id: '/tools'
      path: '/tools'
      fullPath: '/tools'
      preLoaderRoute: typeof ToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify-email': {
      id: '/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof VerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categories/$slug': {
      id: '/categories/$slug'
      path: '/categories/$slug'
      fullPath: '/categories/$slug'
      preLoaderRoute: typeof CategoriesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guides/': {
      id: '/guides/'
      path: '/guides'
      fullPath: '/guides/'
      preLoaderRoute: typeof GuidesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guides/$slug': {
      id: '/guides/$slug'
      path: '/guides/$slug'
      fullPath: '/guides/$slug'
      preLoaderRoute: typeof GuidesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news/': {
      id: '/news/'
      path: '/news'
      fullPath: '/news/'
      preLoaderRoute: typeof NewsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news/$slug': {
      id: '/news/$slug'
      path: '/news/$slug'
      fullPath: '/news/$slug'
      preLoaderRoute: typeof NewsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  FlowRoute: FlowRoute,
  LoginRoute: LoginRoute,
  ProfileRoute: ProfileRoute,
  TimelineRoute: TimelineRoute,
  ToolsRoute: ToolsRoute,
  VerifyEmailRoute: VerifyEmailRoute,
  CategoriesSlugRoute: CategoriesSlugRoute,
  GuidesSlugRoute: GuidesSlugRoute,
  NewsSlugRoute: NewsSlugRoute,
  GuidesIndexRoute: GuidesIndexRoute,
  NewsIndexRoute: NewsIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
